-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 00:26:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e2PQBa5bVy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e2PQBa5bVy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e2PQBa5bVy` DEFAULT CHARACTER SET utf8 ;
USE `e2PQBa5bVy` ;

-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`Type` (
  `id_type` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`Profile` (
  `scan` VARCHAR(45) NOT NULL,
  `id_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `points` INT NULL,
  PRIMARY KEY (`scan`),
  INDEX `fk_Profile_Type_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_Type`
    FOREIGN KEY (`id_type`)
    REFERENCES `e2PQBa5bVy`.`Type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`Recluse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`Recluse` (
  `id_recluse` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date_entry` DATE NULL,
  `date_left` DATE NULL,
  PRIMARY KEY (`id_recluse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`AlertSituation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`AlertSituation` (
  `id_alertsituation` INT NOT NULL,
  `scan` VARCHAR(45) NOT NULL,
  `id_recluse` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `severity` INT NOT NULL,
  PRIMARY KEY (`id_alertsituation`),
  INDEX `fk_AlertSituation_Profile1_idx` (`scan` ASC) VISIBLE,
  INDEX `fk_AlertSituation_Recluse1_idx` (`id_recluse` ASC) VISIBLE,
  CONSTRAINT `fk_AlertSituation_Profile1`
    FOREIGN KEY (`scan`)
    REFERENCES `e2PQBa5bVy`.`Profile` (`scan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlertSituation_Recluse1`
    FOREIGN KEY (`id_recluse`)
    REFERENCES `e2PQBa5bVy`.`Recluse` (`id_recluse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`Schedule` (
  `id_schedule` INT NOT NULL,
  `scan` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_schedule`),
  INDEX `fk_Schedule_Profile1_idx` (`scan` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Profile1`
    FOREIGN KEY (`scan`)
    REFERENCES `e2PQBa5bVy`.`Profile` (`scan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e2PQBa5bVy`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2PQBa5bVy`.`Appointment` (
  `id_appointment` INT NOT NULL,
  `scan` VARCHAR(45) NOT NULL,
  `id_recluse` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_appointment`),
  INDEX `fk_Appointment_Profile1_idx` (`scan` ASC) VISIBLE,
  INDEX `fk_Appointment_Recluse1_idx` (`id_recluse` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Profile1`
    FOREIGN KEY (`scan`)
    REFERENCES `e2PQBa5bVy`.`Profile` (`scan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Recluse1`
    FOREIGN KEY (`id_recluse`)
    REFERENCES `e2PQBa5bVy`.`Recluse` (`id_recluse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
